"""Add library_type column to libraries table

Revision ID: bea40fc487ba
Revises: 
Create Date: 2025-07-04 15:15:56.028054

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bea40fc487ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libraries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('library_type', sa.Enum('NORME', 'SEMI_NORME', 'LIBRE', name='form', create_constraint=True), nullable=False))
        batch_op.drop_index(batch_op.f('report_id'))
        batch_op.drop_constraint(batch_op.f('libraries_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('report_id')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('library_type', sa.Enum('NORME', 'SEMI_NORME', 'LIBRE', name='form', create_constraint=True), nullable=True))
        batch_op.create_unique_constraint(None, ['library_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Enum('FILOWNER', 'ENGAGEMENT_LEADER', 'TEAM_MANAGER', 'TEAM_MEMBER', 'REVIEWER', 'READ_ONLY', name='role', create_constraint=True), nullable=False))
        batch_op.alter_column('phone_number',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('role')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('library_type')

    with op.batch_alter_table('libraries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('libraries_ibfk_1'), 'reports', ['report_id'], ['id'])
        batch_op.create_index(batch_op.f('report_id'), ['report_id'], unique=True)
        batch_op.drop_column('library_type')

    # ### end Alembic commands ###
